### ISSUE TITLE
Docker installation error

### ISSUE THREAD

**Issue by eromang** [t4d/StalkPhish#30] opened 2020-12-06 18:27 UTC
Hello t4d,

Tried to install StalkPhish on Mac OS X docker.

Have the following error

```
Step 6/13 : RUN pip3 install --upgrade pip
 ---> Running in f3329252cd17
/bin/sh: pip3: not found
ERROR: Service 'stalkphish' failed to build : The command '/bin/sh -c pip3 install --upgrade pip' returned a non-zero code: 127
```

Nice end of week-end and stay safe you and your family 

Eric

**Comment by t4d** [comment] 2020-12-07 12:56
Hi Eric  :)
I can't reproduce this error, with docker or docker-compose, from my point of view all is ok, maybe you should try again (sometimes alpine repositories are hard to reach).
Hope all is well! See you  :)

**Comment by ghost** [comment] 2021-04-13 23:34
I confirm this error on Ubuntu 18.04 and fixed with this Dockerfile

https://pastebin.com/KyhvfkWG

**Comment by t4d** [comment] 2021-04-14 05:51
Ok thank you I will double check

**Comment by t4d** [comment] 2021-05-16 20:42
Sorry for the delay, Dockerfile has been updated, it should be better now. Please let me informed if you have other issues. And thank you for your patience  :)

**Closed as completed** 2021-12-29 08:05 UTC
Labels: bug, Corrected
